import type { ExperienceLevel } from "./onboarding.js";
import type { ResourceType } from "./resources.js";

export type StarterResource = {
  url: string;
  title: string;
  type: ResourceType;
  level: ExperienceLevel;
  description: string;
  skillSlugs: readonly string[];
};

/** Curated catalog. Roadmap steps reference these by URL. */
export const STARTER_RESOURCES: readonly StarterResource[] = [
  /* ------------------------------ Foundations ------------------------------ */
  {
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started",
    title: "MDN: Getting started with the web",
    type: "docs",
    level: "beginner",
    description: "MDN's on-ramp to how the web works: files, browsers, and the tools you need before writing your first page.",
    skillSlugs: ["html"],
  },
  {
    url: "https://learnpythonthehardway.org/book/appendixa.html",
    title: "The Command Line Crash Course",
    type: "article",
    level: "beginner",
    description: "A short, hands-on walk through the shell: moving between folders, creating files, and running commands without fear.",
    skillSlugs: ["linux"],
  },
  {
    url: "https://missing.csail.mit.edu/",
    title: "The Missing Semester of Your CS Education (MIT)",
    type: "course",
    level: "beginner",
    description: "MIT's free lectures on the tools courses skip: the shell, editors, Git, debugging, and automation.",
    skillSlugs: ["linux", "git"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting",
    title: "JavaScript first steps (MDN)",
    type: "docs",
    level: "beginner",
    description: "Variables, strings, conditionals, and loops explained with small runnable examples and self-checks.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/",
    title: "freeCodeCamp: JavaScript Algorithms and Data Structures",
    type: "course",
    level: "beginner",
    description: "A free interactive curriculum that takes you from basic syntax to small projects, with in-browser exercises.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://javascript.info/intro",
    title: "javascript.info: Intro",
    type: "article",
    level: "beginner",
    description: "What JavaScript is, where it runs, and what the language can and can't do in a browser.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://javascript.info/",
    title: "javascript.info",
    type: "article",
    level: "beginner",
    description: "The Modern JavaScript Tutorial: a deep, well-ordered reference from fundamentals to the browser and beyond.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    title: "JavaScript guide (MDN)",
    type: "docs",
    level: "beginner",
    description: "MDN's structured tour of the language: grammar, control flow, functions, objects, classes, and modules.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions",
    title: "Functions (MDN)",
    type: "docs",
    level: "beginner",
    description: "Declaring and calling functions, parameters, scope, closures, and arrow functions.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_objects",
    title: "Working with objects (MDN)",
    type: "docs",
    level: "beginner",
    description: "Creating objects, reading and updating properties, methods, and how `this` behaves.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://www.youtube.com/watch?v=8aGhZQkoFbQ",
    title: "What the heck is the event loop anyway? (JSConf EU)",
    type: "video",
    level: "intermediate",
    description: "Philip Roberts' classic talk that visualises the call stack, callbacks, and the event loop.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://docs.github.com/en/get-started/using-git/about-git",
    title: "Git Handbook (GitHub)",
    type: "docs",
    level: "beginner",
    description: "What version control is, how commits and branches work, and the everyday Git workflow on GitHub.",
    skillSlugs: ["git"],
  },
  {
    url: "https://ohmygit.org/",
    title: "Oh My Git! (interactive)",
    type: "tool",
    level: "beginner",
    description: "An open-source card game that teaches Git by visualising the repository as you run real commands.",
    skillSlugs: ["git"],
  },
  {
    url: "https://git-scm.com/book/en/v2",
    title: "Pro Git book (free)",
    type: "docs",
    level: "intermediate",
    description: "The complete Git book, free online: internals, branching strategies, rewriting history, and server setup.",
    skillSlugs: ["git"],
  },
  {
    url: "https://developer.chrome.com/docs/devtools/overview",
    title: "Chrome DevTools overview",
    type: "docs",
    level: "beginner",
    description: "A map of the browser's built-in tools for inspecting elements, debugging scripts, and watching network calls.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Debugging_JavaScript",
    title: "How to debug JavaScript (MDN)",
    type: "docs",
    level: "beginner",
    description: "Reading error messages, using the console, and stepping through code to find out what actually went wrong.",
    skillSlugs: ["javascript"],
  },
  {
    url: "https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes",
    title: "Writing a great README",
    type: "docs",
    level: "beginner",
    description: "What a README is for and how to structure one so people can understand, run, and contribute to your project.",
    skillSlugs: ["git"],
  },
  {
    url: "https://www.freecodecamp.org/news/how-to-build-a-personal-project/",
    title: "How to think about side projects",
    type: "article",
    level: "beginner",
    description: "Picking a project you'll finish, scoping it small, and turning it into something worth showing.",
    skillSlugs: [],
  },

  /* -------------------------------- Frontend ------------------------------- */
  {
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Accessibility/HTML",
    title: "HTML: A good basis for accessibility (MDN)",
    type: "docs",
    level: "beginner",
    description: "Why semantic HTML is the cheapest accessibility win: headings, landmarks, labels, and buttons that just work.",
    skillSlugs: ["html", "accessibility"],
  },
  {
    url: "https://html.spec.whatwg.org/multipage/",
    title: "HTML living standard",
    type: "docs",
    level: "advanced",
    description: "The authoritative HTML specification. Dense, but the final word on how elements and attributes behave.",
    skillSlugs: ["html"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout",
    title: "CSS layout (MDN)",
    type: "docs",
    level: "beginner",
    description: "Normal flow, flexbox, grid, positioning, and responsive design, each with exercises to check yourself.",
    skillSlugs: ["css"],
  },
  {
    url: "https://web.dev/learn/css",
    title: "web.dev: Learn CSS",
    type: "course",
    level: "beginner",
    description: "Google's free CSS course covering the box model, cascade, specificity, layout, and modern features.",
    skillSlugs: ["css"],
  },
  {
    url: "https://flexboxfroggy.com/",
    title: "Flexbox Froggy",
    type: "tool",
    level: "beginner",
    description: "A browser game where you write flexbox rules to guide frogs to their lily pads.",
    skillSlugs: ["css"],
  },
  {
    url: "https://cssgridgarden.com/",
    title: "Grid Garden",
    type: "tool",
    level: "beginner",
    description: "A companion game to Flexbox Froggy that teaches CSS grid by watering a carrot garden.",
    skillSlugs: ["css"],
  },
  {
    url: "https://react.dev/learn",
    title: "React Learn",
    type: "docs",
    level: "beginner",
    description: "The official React tutorial: components, props, state, and effects, with interactive sandboxes.",
    skillSlugs: ["react"],
  },
  {
    url: "https://react.dev/learn/thinking-in-react",
    title: "Thinking in React",
    type: "article",
    level: "intermediate",
    description: "How to break a UI into components and decide where state should live, step by step.",
    skillSlugs: ["react"],
  },
  {
    url: "https://nextjs.org/learn",
    title: "Next.js Learn",
    type: "course",
    level: "intermediate",
    description: "Build a full dashboard app with the App Router, data fetching, server actions, and auth.",
    skillSlugs: ["nextjs", "react"],
  },
  {
    url: "https://nextjs.org/docs",
    title: "Next.js Docs",
    type: "docs",
    level: "intermediate",
    description: "Reference for routing, rendering, caching, and deployment in Next.js.",
    skillSlugs: ["nextjs"],
  },
  {
    url: "https://web.dev/learn/accessibility",
    title: "web.dev: Accessible to all",
    type: "course",
    level: "intermediate",
    description: "A practical accessibility course: ARIA, focus management, color contrast, and testing with assistive tech.",
    skillSlugs: ["accessibility"],
  },
  {
    url: "https://www.deque.com/axe/devtools/",
    title: "axe DevTools",
    type: "tool",
    level: "intermediate",
    description: "A browser extension that scans pages for accessibility issues and explains how to fix each one.",
    skillSlugs: ["accessibility"],
  },

  /* ------------------------------- TypeScript ------------------------------ */
  {
    url: "https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html",
    title: "TypeScript for the New Programmer",
    type: "docs",
    level: "beginner",
    description: "TypeScript explained for people who are new to JavaScript too: what types are and why they help.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    title: "TypeScript Handbook",
    type: "docs",
    level: "intermediate",
    description: "The official guide to the type system, from basic annotations to modules and declaration files.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html",
    title: "Everyday Types",
    type: "docs",
    level: "beginner",
    description: "The types you'll write every day: primitives, arrays, functions, objects, unions, and literals.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/2/narrowing.html",
    title: "Narrowing",
    type: "docs",
    level: "intermediate",
    description: "How TypeScript refines a union type through checks like typeof, in, equality, and discriminated unions.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces",
    title: "Interfaces vs type aliases",
    type: "docs",
    level: "intermediate",
    description: "The practical differences between `interface` and `type`, and when to reach for each.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-aliases",
    title: "Type aliases",
    type: "docs",
    level: "beginner",
    description: "Naming a type so you can reuse it, including object shapes and unions.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/2/generics.html",
    title: "Generics handbook chapter",
    type: "docs",
    level: "intermediate",
    description: "Writing functions and types that work over many types while keeping full type safety.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.typescriptlang.org/docs/handbook/utility-types.html",
    title: "Utility Types",
    type: "docs",
    level: "intermediate",
    description: "Reference for built-ins like Partial, Pick, Omit, Record, and ReturnType with examples.",
    skillSlugs: ["typescript"],
  },
  {
    url: "https://www.totaltypescript.com/tips",
    title: "Total TypeScript tips",
    type: "article",
    level: "advanced",
    description: "Short, focused tips on advanced patterns: inference, generics, conditional and mapped types.",
    skillSlugs: ["typescript"],
  },

  /* -------------------------------- Backend -------------------------------- */
  {
    url: "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
    title: "Node.js guides",
    type: "docs",
    level: "beginner",
    description: "The official introduction to Node: running JavaScript outside the browser, modules, npm, and the event loop.",
    skillSlugs: ["node", "javascript"],
  },
  {
    url: "https://expressjs.com/en/starter/hello-world.html",
    title: "Express Hello world",
    type: "docs",
    level: "beginner",
    description: "The smallest possible Express server, plus links into routing and middleware.",
    skillSlugs: ["express", "node"],
  },
  {
    url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview",
    title: "MDN: HTTP overview",
    type: "docs",
    level: "beginner",
    description: "Requests, responses, methods, status codes, and headers: the protocol every API speaks.",
    skillSlugs: ["apis"],
  },
  {
    url: "https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md",
    title: "Microsoft REST API guidelines",
    type: "article",
    level: "advanced",
    description: "Microsoft's guidance on consistent REST design: naming, versioning, pagination, errors, and long-running operations.",
    skillSlugs: ["apis"],
  },
  {
    url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
    title: "OWASP Authentication Cheat Sheet",
    type: "docs",
    level: "intermediate",
    description: "Security checklist for login flows: password storage, MFA, session handling, and error messages.",
    skillSlugs: ["auth"],
  },
  {
    url: "https://web.dev/articles/samesite-cookies-explained",
    title: "web.dev: SameSite cookies explained",
    type: "article",
    level: "intermediate",
    description: "What the SameSite attribute does, why browsers changed the default, and how it affects auth cookies.",
    skillSlugs: ["auth"],
  },
  {
    url: "https://www.postgresql.org/docs/current/tutorial.html",
    title: "PostgreSQL tutorial",
    type: "docs",
    level: "beginner",
    description: "The official tutorial: creating tables, querying, joins, aggregates, and transactions.",
    skillSlugs: ["postgres", "sql"],
  },
  {
    url: "https://www.prisma.io/docs/getting-started",
    title: "Prisma docs: Getting started",
    type: "docs",
    level: "intermediate",
    description: "Set up Prisma ORM, model your schema, run migrations, and query a database with type safety.",
    skillSlugs: ["postgres", "typescript"],
  },
  {
    url: "https://use-the-index-luke.com/",
    title: "Use the Index, Luke",
    type: "article",
    level: "advanced",
    description: "A free book on SQL performance for developers: how indexes work and how to write queries that use them.",
    skillSlugs: ["sql", "postgres"],
  },
  {
    url: "https://vitest.dev/guide/",
    title: "Vitest docs",
    type: "docs",
    level: "intermediate",
    description: "Getting started with Vitest: writing tests, mocking, coverage, and watch mode.",
    skillSlugs: ["testing", "typescript"],
  },
  {
    url: "https://www.freecodecamp.org/news/how-to-test-api-endpoints/",
    title: "Testing HTTP APIs (overview)",
    type: "article",
    level: "intermediate",
    description: "An overview of how to test API endpoints: what to assert, tooling options, and common pitfalls.",
    skillSlugs: ["testing", "apis"],
  },

  /* ----------------------------- DevOps & cloud ---------------------------- */
  {
    url: "https://linuxjourney.com/",
    title: "Linux Journey",
    type: "course",
    level: "beginner",
    description: "Bite-sized lessons on the command line, permissions, processes, packages, and networking.",
    skillSlugs: ["linux"],
  },
  {
    url: "https://linuxcommand.org/tlcl.php",
    title: "The Linux command line",
    type: "article",
    level: "beginner",
    description: "William Shotts' free book, from first commands to writing shell scripts.",
    skillSlugs: ["linux"],
  },
  {
    url: "https://docs.docker.com/get-started/",
    title: "Docker Get Started",
    type: "docs",
    level: "beginner",
    description: "Containers explained, then build, run, and share your first image.",
    skillSlugs: ["docker"],
  },
  {
    url: "https://docs.docker.com/compose/",
    title: "Compose overview",
    type: "docs",
    level: "intermediate",
    description: "Define multi-container apps (like an API plus a database) in a single YAML file.",
    skillSlugs: ["docker"],
  },
  {
    url: "https://docs.github.com/en/actions/get-started/quickstart",
    title: "GitHub Actions: Quickstart",
    type: "docs",
    level: "beginner",
    description: "Write your first workflow and run checks automatically on every push and pull request.",
    skillSlugs: ["git"],
  },
  {
    url: "https://about.gitlab.com/topics/ci-cd/",
    title: "What is CI/CD?",
    type: "article",
    level: "beginner",
    description: "Plain-language explanation of continuous integration and delivery, and why teams rely on them.",
    skillSlugs: [],
  },
  {
    url: "https://aws.amazon.com/getting-started/cloud-essentials/",
    title: "AWS Cloud Essentials",
    type: "docs",
    level: "beginner",
    description: "AWS's starting point: core services, pricing basics, and hands-on tutorials.",
    skillSlugs: ["cloud"],
  },
  {
    url: "https://www.cloudskillsboost.google/",
    title: "Google Cloud skills boost",
    type: "course",
    level: "beginner",
    description: "Google Cloud's learning platform with guided labs in a real cloud console.",
    skillSlugs: ["cloud"],
  },
  {
    url: "https://cloud.google.com/docs/get-started",
    title: "GCP getting started",
    type: "docs",
    level: "beginner",
    description: "Set up a Google Cloud project and deploy your first workload.",
    skillSlugs: ["cloud"],
  },
  {
    url: "https://sre.google/sre-book/monitoring-distributed-systems/",
    title: "Google SRE book: Monitoring distributed systems",
    type: "article",
    level: "advanced",
    description: "The four golden signals and how Google thinks about alerting on symptoms rather than causes.",
    skillSlugs: ["system-design", "cloud"],
  },

  /* ----------------------------------- Go ---------------------------------- */
  {
    url: "https://go.dev/tour/",
    title: "A Tour of Go",
    type: "course",
    level: "beginner",
    description: "The official interactive tour: syntax, types, methods, interfaces, and concurrency in your browser.",
    skillSlugs: ["go"],
  },
  {
    url: "https://go.dev/doc/effective_go",
    title: "Effective Go",
    type: "docs",
    level: "intermediate",
    description: "How to write idiomatic Go: naming, formatting, error handling, and common patterns.",
    skillSlugs: ["go"],
  },
  {
    url: "https://go.dev/blog/pipelines",
    title: "Go concurrency patterns",
    type: "article",
    level: "advanced",
    description: "Building pipelines with goroutines and channels, including fan-out, fan-in, and cancellation.",
    skillSlugs: ["go"],
  },
  {
    url: "https://go.dev/tour/concurrency/1",
    title: "Tour: Concurrency",
    type: "course",
    level: "intermediate",
    description: "The concurrency chapter of the Go tour: goroutines, channels, select, and mutexes.",
    skillSlugs: ["go"],
  },
  {
    url: "https://pkg.go.dev/net/http",
    title: "net/http package",
    type: "docs",
    level: "intermediate",
    description: "Reference for Go's standard HTTP client and server.",
    skillSlugs: ["go", "apis"],
  },
  {
    url: "https://go.dev/doc/articles/wiki/",
    title: "Writing Web Applications",
    type: "article",
    level: "beginner",
    description: "Build a small wiki with net/http and html/template, from first handler to validation.",
    skillSlugs: ["go"],
  },
  {
    url: "https://docs.docker.com/language/golang/",
    title: "Go Docker guide",
    type: "docs",
    level: "intermediate",
    description: "Containerise a Go service with multi-stage builds, then run and test it.",
    skillSlugs: ["go", "docker"],
  },
  {
    url: "https://go.dev/blog/context",
    title: "Go blog: Context",
    type: "article",
    level: "intermediate",
    description: "Using context.Context to carry deadlines and cancellation across API boundaries.",
    skillSlugs: ["go"],
  },

  /* ------------------------------ System design ---------------------------- */
  {
    url: "https://github.com/donnemartin/system-design-primer",
    title: "System Design Primer",
    type: "article",
    level: "intermediate",
    description: "A huge open-source collection on designing large systems: scaling, caching, databases, and trade-offs.",
    skillSlugs: ["system-design"],
  },
  {
    url: "https://github.com/donnemartin/system-design-primer#system-design-interview-questions-with-solutions",
    title: "System Design Primer: solutions",
    type: "article",
    level: "advanced",
    description: "Worked solutions to common design questions such as a URL shortener, a web crawler, and a social feed.",
    skillSlugs: ["system-design"],
  },
  {
    url: "https://bytebytego.com/courses/system-design-interview/getting-started",
    title: "ByteByteGo: Getting started",
    type: "article",
    level: "intermediate",
    description: "A framework for approaching design problems and estimating scale, from ByteByteGo.",
    skillSlugs: ["system-design"],
  },
  {
    url: "https://aws.amazon.com/caching/",
    title: "Caching overview",
    type: "docs",
    level: "intermediate",
    description: "Why and where to cache, common strategies, and how caching layers fit into an architecture.",
    skillSlugs: ["system-design", "cloud"],
  },
  {
    url: "https://www.nginx.com/resources/glossary/load-balancing/",
    title: "Load balancing concepts",
    type: "article",
    level: "intermediate",
    description: "What load balancers do and how algorithms like round robin and least connections differ.",
    skillSlugs: ["system-design"],
  },
  {
    url: "https://www.infoq.com/articles/cap-twelve-years-later-how-the-rules-have-changed/",
    title: "CAP Twelve Years Later",
    type: "article",
    level: "advanced",
    description: "Eric Brewer revisits the CAP theorem and explains the nuance that the '2 of 3' framing hides.",
    skillSlugs: ["system-design"],
  },
  {
    url: "https://aws.amazon.com/architecture/",
    title: "AWS Architecture Center",
    type: "docs",
    level: "advanced",
    description: "Reference architectures, diagrams, and best practices for building on AWS.",
    skillSlugs: ["system-design", "cloud"],
  },
];
